version: '3.3'
services:
  db:
    image: mysql:8
    restart: always
    network_mode: host
    logging:
      driver: none
    environment:
      MYSQL_DATABASE: banking
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: andre
      MYSQL_ROOT_USER: root
    volumes:
      - "/opt/mysql_data:/var/lib/mysql"
    ports:
      - "3306:3306"

  backend:
    volumes:
      - .:/usr/src
    environment:
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8000
      - DB_USER=root
      - DB_PASSWD=root
      - DB_ADDR=0.0.0.0
      - DB_PORT=3306
      - DB_NAME=banking
    build:
      dockerfile: Dockerfile
      context: .
    network_mode: host
    ports:
      - "8000:8000"



